### ISSUE TITLE
为什么必须引入img-loader.wxml？

### ISSUE THREAD

**Issue by onfirechenlin** [o2team/wxapp-img-loader#11]
为什么必须引入img-loader.wxml？

**Comment by hihuimin** [comment]
因为目前这个组件的原生实现用的是 template 模板的方式，请参考官方文档： https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/import.html

**Comment by Leader755** [comment]
亲 ，其实没太明白这所谓的预加载。这说白不是先加载一张缩略图占位，等原图加载完成后再替换为原图。与这所谓的预加载没多大关系吧。也许是我理解尚浅。

**Comment by imzhaosir** [comment]
> 亲 ，其实没太明白这所谓的预加载。这说白不是先加载一张缩略图占位，等原图加载完成后再替换为原图。与这所谓的预加载没多大关系吧。也许是我理解尚浅。

你视图滚动到一定的高度，才会开始加载图片。不用之前你打开页面图片就全加载了

**Comment by zhuweiyou** [comment]
原生语法不是有 lazy-load 吗? 这个存在的意义是什么

**Comment by hihuimin** [comment]
> 原生语法不是有 lazy-load 吗? 这个存在的意义是什么

这个是预加载，跟懒加载（lazy load）还是有区别的。作用是对图片进行静默加载，等加载完成后就可以直接使用，此时图片就不会出现 loading 时的空白了

**Comment by zhuweiyou** [comment]
> > 原生语法不是有 lazy-load 吗? 这个存在的意义是什么
> 
> 这个是预加载，跟懒加载（lazy load）还是有区别的。作用是对图片进行静默加载，等加载完成后就可以直接使用，此时图片就不会出现 loading 时的空白了

知道了
