### ISSUE TITLE
这个是不是频繁地调用了setData？

### ISSUE THREAD

**Issue by wangsansi** [o2team/wxapp-img-loader#2]
this.page.setData({ 'imgLoadList': list })

这里，每加载一次图片就setData一次，会不会有性能问题？

**Comment by hihuimin** [comment]
没关系的，在 wxml 循环输出 image 组件时有设置 wx:key，已经在队列里的图片不会重复渲染

**Comment by nelsonkuang** [comment]
https://github.com/nelsonkuang/wechat-starter/blob/master/src/components/img-loader.wpy
请教一下，我把组件改成wepy版的性能会不会有影响？

**Comment by hihuimin** [comment]
大致看了下代码，应该没什么问题哈（PS. 请另外issue 交流哈）
