### ISSUE TITLE
多处使用img-loader组件时偶尔会有加载成功后回调函数不执行的情况

### ISSUE THREAD

**Issue by wangzl1163** [o2team/wxapp-img-loader#5]
循环渲染多个item，每个item包含若干张图片，现在在循环item中加入了img-loader组件，渲染过程中组件在加载图片时会偶尔出现图片加载成功但是未执行回到函数的问题，出现概率比较高。

**Comment by hihuimin** [comment]
我这试了ok.. 能麻烦贴一下你的代码吗，我来排查下，谢谢

**Comment by hihuimin** [comment]
我先关了哈，有问题再讨论~
